spring:
  thymeleaf:
    prefix: classpath:/templates
  jackson:
    serialization.write-dates-as-timestamps: false
  mvc:
    favicon:
      enabled: true
    locale: pt_BR
  multipart:
    maxFileSize: 100MB
    maxRequestSize: 100MB
server.error.whitelabel.enabled: false
---
spring:
  thymeleaf:
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  datasource:
        url: jdbc:mysql://sql10.freemysqlhosting.net:3306/sql10203131
        username: sql10203131
        password: FvxVYxGLaB
        driver-class-name: com.mysql.jdbc.Driver
logging:
  file: ./ebenezer-console.log
  level.org:
    springframework.web: DEBUG
    hibernate: ERROR