spring:
  profiles.active: development
  thymeleaf:
    prefix: classpath:/templates
  jackson:
    serialization.write-dates-as-timestamps: false
  jpa.properties.hibernate.default_schema: CTEBENEZER
  mvc:
    favicon:
      enabled: true
    locale: pt_BR
  multipart:
    maxFileSize: 1024KB
    maxRequestSize: 1024KB
server.error.whitelabel.enabled: false
---
spring:
  profiles: development
  thymeleaf:
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS CTEBENEZER 
    platform: h2
---
spring:
  profiles: production
  thymeleaf:
    cache: true
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL
logging:
  file: ./ebenezer-console.log
  level.org:
    springframework.web: DEBUG
    hibernate: ERROR